USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB;
USE DATABASE ECOMMERCE_DB;

CREATE SCHEMA IF NOT EXISTS B_RAW; -- BRONZE LAYER
CREATE SCHEMA IF NOT EXISTS S_STAGING; -- SILVER LAYER
CREATE SCHEMA IF NOT EXISTS G_MARTS; -- GOLD LAYER

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
WITH
WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS ECOMMERCE_DEV;

-- GRATING DB LEVEL ACCESS
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE ECOMMERCE_DEV;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ECOMMERCE_DB TO ROLE ECOMMERCE_DEV;
GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
ON SCHEMA ECOMMERCE_DB.B_RAW TO ROLE ECOMMERCE_DEV;
GRANT CREATE TABLE, CREATE STAGE, CREATE VIEW
ON SCHEMA ECOMMERCE_DB.S_STAGING TO ROLE ECOMMERCE_DEV;
GRANT CREATE TABLE, CREATE VIEW
ON SCHEMA ECOMMERCE_DB.G_MARTS TO ROLE ECOMMERCE_DEV;
GRANT USAGE, OPERATE ON WAREHOUSE TRANSFORM_WH TO ROLE ECOMMERCE_DEV;

-- ASSIGNING THE ROLE TO USER
GRANT ROLE ECOMMERCE_DEV TO USER BESTLITTLE326;

USE ROLE ECOMMERCE_DEV;
USE DATABASE ECOMMERCE_DB;
USE WAREHOUSE TRANSFORM_WH;
USE SCHEMA B_RAW;

SHOW WAREHOUSES;
SHOW DATABASES;