-- LOAD RAW DATA (BRONZE LAYER)

USE SCHEMA ECOMMERCE_DB.B_RAW;

CREATE STAGE IF NOT EXISTS RAW_STAGE
COMMENT = 'INTERNAL STAGE FOR OLIST E-COMMERCE CSV FILES UPLOAD';

CREATE FILE FORMAT IF NOT EXISTS OLIST_CSV_FMT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER ='\N'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL','NULL','','NA')
EMPTY_FIELD_AS_NULL = TRUE
DATE_FORMAT = 'AUTO'
TIMESTAMP_FORMAT = 'AUTO';

-- CREATE AND LOAD ORDERS TABLE
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.B_RAW.ORDERS(
    ORDER_ID  VARCHAR,
    CUSTOMER_ID VARCHAR,
    ORDER_STATUS VARCHAR,
    ORDER_PURCHASE_TIMESTAMP VARCHAR,
    ORDER_APPROVED_AT VARCHAR,
    ORDER_DELIVERED_CARRIER_DATE VARCHAR,
    ORDER_DELIVERED_CUSTOMER_DATE VARCHAR,
    ORDER_ESTIMATED_DELIVERY_DATE VARCHAR
);

COPY INTO ECOMMERCE_DB.B_RAW.ORDERS
FROM @ECOMMERCE_DB.B_RAW.RAW_STAGE/OLIST_ORDERS_DATASET.CSV.GZ
FILE_FORMAT = (FORMAT_NAME = 'ECOMMERCE_DB.B_RAW.OLIST_CSV_FMT')
ON_ERROR = 'ABORT_STATEMENT';

-- VERIFY THE LOAD
SELECT COUNT(*) FROM ECOMMERCE_DB.B_RAW.ORDERS;

-- CREATE AND LOAD ORDER ITEMS
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.B_RAW.ORDER_ITEMS (
  ORDER_ID              VARCHAR,
  ORDER_ITEM_ID         VARCHAR,
  PRODUCT_ID            VARCHAR,
  SELLER_ID             VARCHAR,
  SHIPPING_LIMIT_DATE   VARCHAR,
  PRICE                 VARCHAR,
  FREIGHT_VALUE         VARCHAR
);

COPY INTO ECOMMERCE_DB.B_RAW.ORDER_ITEMS
  FROM @ECOMMERCE_DB.B_RAW.RAW_STAGE/OLIST_ORDER_ITEMS_DATASET.CSV.GZ
  FILE_FORMAT = (FORMAT_NAME = 'ECOMMERCE_DB.B_RAW.OLIST_CSV_FMT')
  ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) FROM ECOMMERCE_DB.B_RAW.ORDER_ITEMS;

-- CREATE AND LOAD CUSTOMERS
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.B_RAW.CUSTOMERS (
  CUSTOMER_ID               VARCHAR,
  CUSTOMER_UNIQUE_ID        VARCHAR,
  CUSTOMER_ZIP_CODE_PREFIX  VARCHAR,
  CUSTOMER_CITY             VARCHAR,
  CUSTOMER_STATE            VARCHAR
);

COPY INTO ECOMMERCE_DB.B_RAW.CUSTOMERS
  FROM @ECOMMERCE_DB.B_RAW.RAW_STAGE/OLIST_CUSTOMERS_DATASET.CSV.GZ
  FILE_FORMAT = (FORMAT_NAME = 'ECOMMERCE_DB.B_RAW.OLIST_CSV_FMT')
  ON_ERROR = 'ABORT_STATEMENT';

-- CREATE AND LOAD PRODUCTS
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.B_RAW.PRODUCTS (
  PRODUCT_ID                   VARCHAR,
  PRODUCT_CATEGORY_NAME        VARCHAR,
  PRODUCT_NAME_LENGHT          VARCHAR,  -- NOTE: SOURCE HAS TYPO, KEEP IT
  PRODUCT_DESCRIPTION_LENGHT   VARCHAR,
  PRODUCT_PHOTOS_QTY           VARCHAR,
  PRODUCT_WEIGHT_G             VARCHAR,
  PRODUCT_LENGTH_CM            VARCHAR,
  PRODUCT_HEIGHT_CM            VARCHAR,
  PRODUCT_WIDTH_CM             VARCHAR
);

COPY INTO ECOMMERCE_DB.B_RAW.PRODUCTS
  FROM @ECOMMERCE_DB.B_RAW.RAW_STAGE/OLIST_PRODUCTS_DATASET.CSV.GZ
  FILE_FORMAT = (FORMAT_NAME = 'ECOMMERCE_DB.B_RAW.OLIST_CSV_FMT')
  ON_ERROR = 'ABORT_STATEMENT';

-- SELLERS
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.B_RAW.SELLERS (
  SELLER_ID              VARCHAR,
  SELLER_ZIP_CODE_PREFIX VARCHAR,
  SELLER_CITY            VARCHAR,
  SELLER_STATE           VARCHAR
);
COPY INTO ECOMMERCE_DB.B_RAW.SELLERS
  FROM @ECOMMERCE_DB.B_RAW.RAW_STAGE/OLIST_SELLERS_DATASET.CSV.GZ
  FILE_FORMAT = (FORMAT_NAME = 'ECOMMERCE_DB.B_RAW.OLIST_CSV_FMT') ON_ERROR='ABORT_STATEMENT';

-- PAYMENTS
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.B_RAW.ORDER_PAYMENTS (
  ORDER_ID               VARCHAR,
  PAYMENT_SEQUENTIAL     VARCHAR,
  PAYMENT_TYPE           VARCHAR,
  PAYMENT_INSTALLMENTS   VARCHAR,
  PAYMENT_VALUE          VARCHAR
);
COPY INTO ECOMMERCE_DB.B_RAW.ORDER_PAYMENTS
  FROM @ECOMMERCE_DB.B_RAW.RAW_STAGE/OLIST_ORDER_PAYMENTS_DATASET.CSV.GZ
  FILE_FORMAT = (FORMAT_NAME = 'ECOMMERCE_DB.B_RAW.OLIST_CSV_FMT') ON_ERROR='ABORT_STATEMENT';


  -- REVIEWS
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.B_RAW.ORDER_REVIEWS (
  REVIEW_ID              VARCHAR,
  ORDER_ID               VARCHAR,
  REVIEW_SCORE           VARCHAR,
  REVIEW_COMMENT_TITLE   VARCHAR,
  REVIEW_COMMENT_MESSAGE VARCHAR,
  REVIEW_CREATION_DATE   VARCHAR,
  REVIEW_ANSWER_TIMESTAMP VARCHAR
);
COPY INTO ECOMMERCE_DB.B_RAW.ORDER_REVIEWS
  FROM @ECOMMERCE_DB.B_RAW.RAW_STAGE/OLIST_ORDER_REVIEWS_DATASET.CSV.GZ
  FILE_FORMAT = (FORMAT_NAME= 'ECOMMERCE_DB.B_RAW.OLIST_CSV_FMT') ON_ERROR = 'ABORT_STATEMENT';

-- CATEGORY TRANSLATIONS
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.B_RAW.PRODUCT_CATEGORY_TRANSLATIONS (
  PRODUCT_CATEGORY_NAME         VARCHAR,
  PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR
);
COPY INTO ECOMMERCE_DB.B_RAW.PRODUCT_CATEGORY_TRANSLATIONS
  FROM @ECOMMERCE_DB.B_RAW.RAW_STAGE/OLIST_PRODUCT_CATEGORY_NAME_TRANSLATION.CSV.GZ
  FILE_FORMAT = (FORMAT_NAME = 'ECOMMERCE_DB.B_RAW.OLIST_CSV_FMT') ON_ERROR='ABORT_STATEMENT';



SELECT 'ORDERS' AS TBL, 
COUNT(*) AS ORDER_ROWS 
FROM ECOMMERCE_DB.B_RAW.ORDERS
UNION ALL
SELECT 'ORDER_ITEMS', COUNT(*) FROM ECOMMERCE_DB.B_RAW.ORDER_ITEMS
UNION ALL
SELECT 'CUSTOMERS', COUNT(*) FROM ECOMMERCE_DB.B_RAW.CUSTOMERS
UNION ALL
SELECT 'PRODUCTS', COUNT(*) FROM ECOMMERCE_DB.B_RAW.PRODUCTS
UNION ALL
SELECT 'SELLERS', COUNT(*) FROM ECOMMERCE_DB.B_RAW.SELLERS
UNION ALL
SELECT 'ORDER_PAYMENTS', COUNT(*) FROM ECOMMERCE_DB.B_RAW.ORDER_PAYMENTS
UNION ALL
SELECT 'ORDER_REVIEWS', COUNT(*) FROM ECOMMERCE_DB.B_RAW.ORDER_REVIEWS
UNION ALL
SELECT 'CATEGORY_TRANSLATIONS', COUNT(*) FROM ECOMMERCE_DB.B_RAW.PRODUCT_CATEGORY_TRANSLATIONS
ORDER BY ORDER_ROWS DESC;
